### ISSUE TITLE
ExcludeChildren dependency?

### ISSUE THREAD

**Issue by nyeholt** [sheadawson/silverstripe-newsly#5]
Did this get dropped as a dependency (or was it never there?) 

"micschk/silverstripe-excludechildren"

**Comment by sheadawson** [comment]
Yeah I dropped it for lumberjack as it's a bit better and a commercially supported module

**Comment by nyeholt** [comment]
Ah right. Guess you just saw the config reference cwusing problems :)

**Comment by sheadawson** [comment]
Yeap, cheers!

On Tue, Dec 8, 2015 at 10:46 AM, Marcus notifications@github.com wrote:

> Closed #5 https://github.com/sheadawson/silverstripe-newsly/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sheadawson/silverstripe-newsly/issues/5#event-484938442
> .

## 

_Shea Dawson_
Web Developer
LiveSource

_mobile_ +64 20 4028 5647
_skype_ squatchnz
_email_ shea@livesource.co.nz
*web *www.livesource.co.nz
